### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by CAYdenberg** [kulbakin/beanstream#1]
Hi,

I have little experience with Composer or autoloaders so I apologize if this has an obvious solution.

I have installed using composer and am including with `require('vendor/autoload.php')` in the first functional line of code on my site. I'm essentially just using the sample code (http://developer.beanstream.com/documentation/your-first-integration/) with my own merchant ID and API passcode. Getting the following error:

Fatal error: Call to undefined function Beanstream\msgfmt_format_message() in C:\wamp\www\met2\vendor\beanstream\beanstream\src\Beanstream\communications\Endpoints.php on line 105

I'm pretty sure the autoloader is working because if I don't include the require statement the code terminates earlier.

I am using this in the context of Wordpress but I've successfully integrated with composer according to this plan: https://roots.io/using-composer-with-wordpress/

Not sure what else to try. Can you help me diagnose? What else do you need to know?

**Comment by kulbakin** [comment]
I'm not sure why you reporting it here, there is no such file in this repository src\Beanstream\communications\Endpoints.php
This repository is called "propa/beanstream", but it seems you use another beanstream api called "beanstream/beanstream", github link https://github.com/Beanstream-DRWP/beanstream-php
So if you want to try this one, use proper "require" rule in your composer file

**Comment by CAYdenberg** [comment]
You are right and I just discovered the same thing. It appears their repo was forked from your and I got my wires crossed. Apologies.
